server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbblogapi?useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./blog.db
  jpa:
    generate-ddl: on
    hibernate:
      ddl.auto: update
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
key: key
debug: true

